// Extracted from LaBrute core/src/constants.ts and types.ts

export const StepType = {
  Saboteur: 0,
  Leave: 1,
  Arrive: 2,
  Trash: 3,
  Steal: 4,
  Trap: 5,
  Heal: 6,
  Resist: 7,
  Survive: 8,
  Hit: 9,
  FlashFlood: 10,
  Hammer: 11,
  Poison: 12,
  Bomb: 13,
  Hypnotise: 14,
  Move: 15,
  Eat: 16,
  MoveBack: 17,
  Equip: 18,
  AttemptHit: 19,
  Block: 20,
  Evade: 21,
  Sabotage: 22,
  Disarm: 23,
  Death: 24,
  Throw: 25,
  End: 26,
  Counter: 27,
  SkillActivate: 28,
  SkillExpire: 29,
  Spy: 30,
  Vampirism: 31,
  Haste: 32,
  Treat: 33,
  DropShield: 34,
  Regeneration: 35
};

export const BASE_FIGHTER_STATS = {
  reversal: 0,
  evasion: 0.1,
  dexterity: 0.2,
  block: -0.25,
  accuracy: 0,
  disarm: 0.05,
  combo: 0,
  deflect: 0,
  tempo: 1.2,
  criticalChance: 0.05,
  criticalDamage: 1.5,
};

export const BARE_HANDS_DAMAGE = 5;

// Weapon definitions from core/src/brute/weapons.ts
export const weapons = {
  axe: {
    name: 'axe',
    odds: 3000,
    types: ['heavy'],
    tempo: 2.2,
    reversal: 0.1,
    evasion: -0.3,
    dexterity: -0.2,
    block: -0.3,
    accuracy: 0.5,
    disarm: 0.1,
    combo: -0.4,
    deflect: 0,
    damage: 50,
    reach: 1,
    toss: 8
  },
  baton: {
    name: 'baton',
    odds: 100,
    types: ['long'],
    tempo: 0.8,
    reversal: 0.3,
    evasion: 0.05,
    dexterity: 0,
    block: 0.2,
    accuracy: 0,
    disarm: 0.1,
    combo: 0.1,
    deflect: 0,
    damage: 6,
    reach: 3,
    toss: 5
  },
  broadsword: {
    name: 'broadsword',
    odds: 500,
    types: ['sharp'],
    tempo: 1,
    reversal: 0.1,
    evasion: 0,
    dexterity: 0,
    block: 0.15,
    accuracy: 0,
    disarm: 0.15,
    combo: 0,
    deflect: 0,
    damage: 14,
    reach: 1,
    toss: 8
  },
  bumps: {
    name: 'bumps',
    odds: 50,
    types: ['heavy', 'blunt'],
    tempo: 2.5,
    reversal: 0.3,
    evasion: -0.3,
    dexterity: -0.35,
    block: -0.3,
    accuracy: 0.5,
    disarm: 0.1,
    combo: -0.6,
    deflect: 0,
    damage: 55,
    reach: 1,
    toss: 10
  },
  fan: {
    name: 'fan',
    odds: 50,
    types: ['fast'],
    tempo: 0.28,
    reversal: -0.4,
    evasion: 0.6,
    dexterity: 0.5,
    block: -0.5,
    accuracy: 0.3,
    disarm: -0.3,
    combo: 0.5,
    deflect: 0.25,
    damage: 4,
    reach: 0,
    toss: 2
  },
  flail: {
    name: 'flail',
    odds: 400,
    types: ['heavy'],
    tempo: 1,
    reversal: 0.39,
    evasion: 0,
    dexterity: 0,
    block: 0,
    accuracy: -0.1,
    disarm: -0.1,
    combo: 0,
    deflect: 0,
    damage: 19,
    reach: 1,
    toss: 6
  },
  fryingPan: {
    name: 'fryingPan',
    odds: 40,
    types: ['blunt'],
    tempo: 0.8,
    reversal: -0.1,
    evasion: 0.15,
    dexterity: 0.1,
    block: 0.3,
    accuracy: 0.3,
    disarm: 0,
    combo: 0,
    deflect: 0,
    damage: 17,
    reach: 0,
    toss: 8
  },
  halbard: {
    name: 'halbard',
    odds: 200,
    types: ['long', 'sharp'],
    tempo: 1.8,
    reversal: 0.1,
    evasion: -0.1,
    dexterity: -0.1,
    block: 0,
    accuracy: 0,
    disarm: 0.3,
    combo: -0.2,
    deflect: 0,
    damage: 24,
    reach: 5,
    toss: 10
  },
  hatchet: {
    name: 'hatchet',
    odds: 400,
    types: ['heavy', 'sharp'],
    tempo: 1,
    reversal: 0,
    evasion: 0,
    dexterity: 0,
    block: 0,
    accuracy: 0.1,
    disarm: 0,
    combo: 0,
    deflect: 0,
    damage: 17,
    reach: 0,
    toss: 6
  },
  keyboard: {
    name: 'keyboard',
    odds: 100,
    types: ['blunt'],
    tempo: 0.7,
    reversal: 0,
    evasion: 0,
    dexterity: 0,
    block: 0,
    accuracy: 0.3,
    disarm: 0,
    combo: 0.3,
    deflect: 0,
    damage: 7,
    reach: 1,
    toss: 5
  },
  knife: {
    name: 'knife',
    odds: 200,
    types: ['fast', 'sharp'],
    tempo: 0.5,
    reversal: -0.15,
    evasion: 0.1,
    dexterity: 0.25,
    block: -0.15,
    accuracy: 0,
    disarm: -0.1,
    combo: 0.3,
    deflect: 0,
    damage: 7,
    reach: 0,
    toss: 3
  },
  lance: {
    name: 'lance',
    odds: 100,
    types: ['long'],
    tempo: 0.8,
    reversal: 0.15,
    evasion: 0,
    dexterity: 0.05,
    block: 0,
    accuracy: 0,
    disarm: 0.1,
    combo: 0.1,
    deflect: 0,
    damage: 10,
    reach: 4,
    toss: 5
  },
  leek: {
    name: 'leek',
    odds: 40,
    types: [],
    tempo: 0.5,
    reversal: 0,
    evasion: 0.5,
    dexterity: 0.5,
    block: 0,
    accuracy: 0.4,
    disarm: 0,
    combo: 0.3,
    deflect: 0,
    damage: 5,
    reach: 1,
    toss: 3
  },
  mammothBone: {
    name: 'mammothBone',
    odds: 250,
    types: ['heavy', 'blunt'],
    tempo: 2.2,
    reversal: 0,
    evasion: -0.15,
    dexterity: -0.15,
    block: -0.1,
    accuracy: 0.3,
    disarm: 0,
    combo: -0.3,
    deflect: 0,
    damage: 32,
    reach: 2,
    toss: 10
  },
  morningStar: {
    name: 'morningStar',
    odds: 250,
    types: ['heavy'],
    tempo: 1.5,
    reversal: 0.15,
    evasion: -0.05,
    dexterity: -0.05,
    block: -0.3,
    accuracy: 0.1,
    disarm: 0.1,
    combo: -0.1,
    deflect: 0,
    damage: 26,
    reach: 1,
    toss: 8
  },
  mug: {
    name: 'mug',
    odds: 400,
    types: ['blunt', 'thrown'],
    tempo: 0.7,
    reversal: 0,
    evasion: 0,
    dexterity: 0,
    block: 0,
    accuracy: 0.3,
    disarm: 0,
    combo: 0.1,
    deflect: 0,
    damage: 8,
    reach: 0,
    toss: 4
  },
  noodleBowl: {
    name: 'noodleBowl',
    odds: 300,
    types: ['thrown'],
    tempo: 0.16,
    reversal: 0,
    evasion: 0,
    dexterity: 0,
    block: 0,
    accuracy: 0.4,
    disarm: 0,
    combo: 0,
    deflect: 0,
    damage: 10,
    reach: 0,
    toss: 2
  },
  piopio: {
    name: 'piopio',
    odds: 5,
    types: ['thrown'],
    tempo: 0.12,
    reversal: 0,
    evasion: 0,
    dexterity: 0,
    block: 0,
    accuracy: 0.5,
    disarm: 0,
    combo: 0,
    deflect: 0,
    damage: 3,
    reach: 0,
    toss: 2
  },
  racquet: {
    name: 'racquet',
    odds: 70,
    types: [],
    tempo: 0.8,
    reversal: 0.1,
    evasion: 0.1,
    dexterity: 0.1,
    block: 0.1,
    accuracy: 0.05,
    disarm: 0,
    combo: 0.05,
    deflect: 0.3,
    damage: 11,
    reach: 1,
    toss: 5
  },
  sai: {
    name: 'sai',
    odds: 200,
    types: ['fast'],
    tempo: 0.6,
    reversal: 0.5,
    evasion: 0.1,
    dexterity: 0.25,
    block: 0.15,
    accuracy: 0,
    disarm: 0.5,
    combo: 0,
    deflect: 0,
    damage: 9,
    reach: 0,
    toss: 4
  },
  scimitar: {
    name: 'scimitar',
    odds: 70,
    types: ['sharp'],
    tempo: 0.8,
    reversal: 0,
    evasion: 0.05,
    dexterity: 0.05,
    block: 0,
    accuracy: 0.05,
    disarm: 0.05,
    combo: 0.05,
    deflect: 0,
    damage: 11,
    reach: 0,
    toss: 6
  },
  shuriken: {
    name: 'shuriken',
    odds: 200,
    types: ['fast', 'thrown'],
    tempo: 0.14,
    reversal: 0,
    evasion: 0.1,
    dexterity: 0,
    block: 0,
    accuracy: 0.3,
    disarm: 0,
    combo: 0,
    deflect: 0,
    damage: 5,
    reach: 0,
    toss: 2
  },
  sword: {
    name: 'sword',
    odds: 100,
    types: ['sharp'],
    tempo: 0.9,
    reversal: 0,
    evasion: 0,
    dexterity: 0.05,
    block: 0.05,
    accuracy: 0,
    disarm: 0.05,
    combo: 0,
    deflect: 0,
    damage: 12,
    reach: 1,
    toss: 7
  },
  trident: {
    name: 'trident',
    odds: 100,
    types: ['long'],
    tempo: 1.2,
    reversal: 0.1,
    evasion: -0.05,
    dexterity: 0,
    block: 0,
    accuracy: 0,
    disarm: 0.25,
    combo: 0,
    deflect: 0,
    damage: 16,
    reach: 3,
    toss: 7
  },
  trombone: {
    name: 'trombone',
    odds: 50,
    types: ['blunt'],
    tempo: 1.1,
    reversal: 0,
    evasion: 0,
    dexterity: 0,
    block: 0.2,
    accuracy: 0.3,
    disarm: 0,
    combo: 0,
    deflect: 0,
    damage: 20,
    reach: 2,
    toss: 8
  },
  whip: {
    name: 'whip',
    odds: 60,
    types: ['long'],
    tempo: 1.5,
    reversal: 0.35,
    evasion: -0.1,
    dexterity: 0.3,
    block: -0.2,
    accuracy: -0.2,
    disarm: 0.35,
    combo: -0.1,
    deflect: 0,
    damage: 12,
    reach: 5,
    toss: 7
  }
};

// Skills from core/src/brute/skills.ts
export const skills = {
  herculeanStrength: { name: 'herculeanStrength', type: 'booster' },
  felineAgility: { name: 'felineAgility', type: 'booster' },
  lightningBolt: { name: 'lightningBolt', type: 'booster' },
  vitality: { name: 'vitality', type: 'booster' },
  immortality: { name: 'immortality', type: 'booster' },
  reconnaissance: { name: 'reconnaissance', type: 'booster' },
  weaponsMaster: { name: 'weaponsMaster', type: 'passive' },
  martialArts: { name: 'martialArts', type: 'passive' },
  sixthSense: { name: 'sixthSense', type: 'passive' },
  shield: { name: 'shield', type: 'passive' },
  armor: { name: 'armor', type: 'passive' },
  survival: { name: 'survival', type: 'passive' },
  fierceBrute: { name: 'fierceBrute', type: 'super' },
  thief: { name: 'thief', type: 'super' },
  tragicPotion: { name: 'tragicPotion', type: 'super' },
  net: { name: 'net', type: 'super' },
  bomb: { name: 'bomb', type: 'super' },
  hammer: { name: 'hammer', type: 'super' }
};

// Animation speed constants
export const ANIMATION_SPEED = {
  MOVE: 800,
  HIT: 400,
  BLOCK: 300,
  EVADE: 500,
  DEATH: 1000,
  EQUIP: 300,
  THROW: 600
};

// Fight positions
export const ARENA_WIDTH = 550;
export const ARENA_LEFT = 125;
export const ARENA_RIGHT = ARENA_LEFT + ARENA_WIDTH;